services:
    app_casebox_core.service.casebox_core_service:
        class: App\CaseboxCoreBundle\Service\CaseboxCoreService
        calls:
            - [ setContainer, [ '@service_container' ] ]

    app_casebox_core.service.casebox_core_command_service:
        class: App\CaseboxCoreBundle\Service\CaseboxCoreCommandService
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # entity
    app_casebox_core.entity.core:
        class: App\CaseboxCoreBundle\Entity\Core

    # Repository
    app_casebox_core.repository.core_repository:
        class: App\CaseboxCoreBundle\Repository\CoreRepository
        calls:
            - [ setContainer, [ '@service_container' ] ]
            - [ setDbDir, [ '%database_dir%' ] ]
