# Redis configuration
parameters:
    redis:
        scheme: 'tcp'
        host: '127.0.0.1'
        port: 6379
        routes:
            - { route: '/echo', class: 'Ratchet\Server\EchoServer', params: ~ }