# Redis configuration
parameters:
    ratchet:
        host: 0.0.0.0
        port: 8081
        routes:
            - { route: '/logs', class: 'App\DashboardBundle\Service\WebSocketComponent\LoggingMessageComponent', params: [ '*' ] }

