services:
    app_system_service.service.system_services_command_service:
        class: App\SystemServiceBundle\Service\SystemServicesCommandService

    app_system_service.service.system_services_service:
        class: App\SystemServiceBundle\Service\SystemServicesService
        calls:
            - [setContainer, ['@service_container']]